### ISSUE TITLE
[EPIC] - Domain-Storytelling

### ISSUE THREAD

**Issue by levinkerschberger** [dqualizer/dqAnalyzer-react#13]
## Description
As a domain-expert who got knowledge about workflows in the domain, I want to import and list domain-stories / workflows of activities, so I can create Runtime Quality Analysis Definitions (RQA Definitions) of those workflows / domain-stories.

## Issues

- [ ] Issue one
- [ ] Issue two
- [ ] Issue three

## Acceptance criteria
- [ ] It is possible to import multiple domain-stories to the domain
- [ ] The user is able to choose the activities, which belong to the domain-story
- [ ] The created domain storys are saved somewhere and are selectable e.g. in the loadtest specification menu.
- [ ] Selecting a domain-story hides all other domain-stories in the graph

## Additional context

Add any other context or screenshots about the research request here.
